### ISSUE TITLE
'AWFileHash.h' file not found

### ISSUE THREAD

**Issue by duongthai910** [vidurajith-darshana/react-native-app-integrity-checksum#1]
I am having this problem when running app by Xcode, I have already added "AWFileHash" in Podfile and did "Pod install", version of AWFileHash in Podfile.lock is 0.2.0.
<img width="1200" alt="Screenshot 2023-11-13 at 13 52 08" src="https://github.com/vidurajith-darshana/react-native-app-integrity-checksum/assets/128686322/869ac80c-5e49-4ddb-bd08-dd381cd8bbc9">

**Comment by vidurajith-darshana** [comment]
Did you check the example project is working?

**Comment by duongthai910** [comment]
I tried to clear my project and build several times but still got the error, I just removed the import line and rewrote the same and it works, don't know what's going on.

**Comment by vidurajith-darshana** [comment]
Okay, I will mark the issue as closed!
